# Generated by Django 2.0.7 on 2018-08-09 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0003_auto_20180808_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 9, 53, 42, 32381, tzinfo=utc)),
        ),
    ]
