# Generated by Django 2.0.7 on 2018-08-09 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0005_auto_20180809_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 11, 43, 20, 205117, tzinfo=utc)),
        ),
    ]
