# Generated by Django 2.0.7 on 2018-08-09 16:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0006_auto_20180809_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 16, 50, 24, 635219, tzinfo=utc)),
        ),
    ]
