# Generated by Django 2.0.7 on 2018-08-10 11:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0008_auto_20180810_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 11, 18, 22, 194209, tzinfo=utc)),
        ),
    ]
