# Generated by Django 2.0.7 on 2018-08-10 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0010_auto_20180810_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 17, 6, 12, 219978, tzinfo=utc)),
        ),
    ]
